% \VignetteIndexEntry{miRNATargetTutorial}
% \VignetteKeywords{target gene table, miRNA, gene id conversion}
% \VignettePackage{miRNATarget}
\documentclass[12pt]{article}
<<echo=FALSE>>=
options(width=65)
@ 
\SweaveOpts{eps=FALSE,echo=TRUE}
\usepackage{times}
\usepackage{hyperref}
\usepackage{fullpage}

\newcommand{\Robject}[1]{{\texttt{#1}}}
\newcommand{\Rfunction}[1]{{\texttt{#1}}}
\newcommand{\Rpackage}[1]{{\texttt{#1}}}
\newcommand{\Rclass}[1]{{\texttt{#1}}}
\newcommand{\Rmethod}[1]{{\texttt{#1}}}
\newcommand{\Rfunarg}[1]{{\texttt{#1}}}

\begin{document}
\setlength{\parskip}{1\baselineskip}
\setlength{\parindent}{0pt}
\setcounter{secnumdepth}{1} 
\title{The miRNATarget data User's Guide}
\author{Y-h. Taguchi}
\date{Modified: December 7, 2013  Compiled: \today}
\maketitle


%\bibliographystyle{plain}
\tableofcontents



\section{Overview}


The \Rpackage{miRNATarget} package contains  
miRNA target gene table  for human/mouse, gene id conversion table and miRNA conservation table, which are intended for the usage of \Rpackage{MiRaGE}.
\Rpackage{MiRaGE} is the software package which infers target gene regulation of miRNAs via the algorithm employed in MiRaGE Server, http://www.granular.com/MiRaGE/.

Since this experimental package is only for the usage with \Rpackage{MiRaGE}, please refer to vignette in \Rpackage{MiRaGE} for details about this experimental package.
\Rpackage{MiRaGE}  and citations\cite{yoshizawa,iConceptpress} there explain what  these data are, how to generate them from scratch and how to use them. In order to avoid the duplicate explanation, no detailed explanation will not be here.

<<input>>=
library(miRNATarget)
data(MM_refseq_to_ensembl_gene_id)
data(TBL2_MM)
data(MM_conv_id)
@

\begin{thebibliography}{1}
\bibitem{yoshizawa} Yoshizawa, M., Taguchi, Y-h., and Yasuda, J. (2011), Inference of Gene Regulation via miRNAs During ES Cell
Differentiation Using MiRaGE Method. Int J Mol Sci 12(12):9265-9276
\bibitem{iConceptpress}
Taguchi, Y-h. (2013). Inference of Target Gene Regulation by miRNA via MiRaGE Server. Introduction to Genetics - DNA Methylation, Histone Modification and Gene Regulation. ISBN: 978-1477554-94-4. iConcept Press. Retrieved from http://www.iconceptpress.com/books/ 
IntroductionToGeneticsDNAMethylationHistoneModificationAndGeneRegulation/
\end{thebibliography}
\end{document}
